### ISSUE TITLE
Interrupted exception on shutdown on Kafka producer

### ISSUE THREAD

**Issue by mswiderski** [vert-x3/vertx-kafka-client#149]
This issue originates from Quarkus application using `quarkus-smallrye-reactive-messaging-kafka`. It is thrown for each and every producer that is created within the application thus occurs  multiple times.

````
2019-10-01 12:03:18,276 ERROR [org.apa.kaf.cli.pro.KafkaProducer] (vert.x-worker-thread-11) [Producer clientId=producer-2] Interrupted while joining ioThread: java.lang.InterruptedException
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Thread.join(Thread.java:1313)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1161)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1138)
	at org.apache.kafka.clients.producer.KafkaProducer.close(KafkaProducer.java:1117)
	at io.vertx.kafka.client.producer.impl.KafkaWriteStreamImpl.lambda$close$12(KafkaWriteStreamImpl.java:238)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
````

Application does not experience any issues and works as expected but this message might be seen as a concern especially that it's printed as ERROR

**Comment by vietj** [comment]
it seems this logging is not performed by Vert.x but by Kafka Client:

```
if (this.ioThread != null) {
    try {
       this.ioThread.join(timeoutMs);
    } catch (InterruptedException t) {
       firstException.compareAndSet(null, new InterruptException(t));
       log.error("Interrupted while joining ioThread", t);
    }
}
```

one interesting question is : what is the thread interrupting the close thread ? can you determine that ?

**Comment by mswiderski** [comment]
correct, it is in Kafka client. the idea from @cescoffier was to hide the exception https://groups.google.com/d/msgid/quarkus-dev/D37E26E9-9CDE-41B9-9E95-B353B750AD06%40gmail.com

let me try to find out what thread is interrupting ....

**Comment by mswiderski** [comment]
@vietj here is what I found so far

````
	VertxThread(Thread).interrupt() line: 985	
	ThreadPoolExecutor$Worker.interruptIfStarted() line: 663	
	ThreadPoolExecutor.interruptWorkers() line: 761	
	ThreadPoolExecutor.shutdownNow() line: 1407	
	WorkerPool.close() line: 43	
	VertxImpl.lambda$deleteCacheDirAndShutdown$25(Handler, AsyncResult) line: 838	
	2050620396.handle(Object) line: not available	
	ContextImpl.lambda$null$0(Handler, AsyncResult, Void) line: 330	
	183555305.handle(Object) line: not available	
	EventLoopContext(ContextImpl).executeTask(T, Handler<T>) line: 369	
	EventLoopContext.lambda$executeAsync$0(Handler) line: 38	
	621014131.run() line: not available	
	AbstractEventExecutor.safeExecute(Runnable) line: 163	
	NioEventLoop(SingleThreadEventExecutor).runAllTasks(long) line: 416	
	NioEventLoop.run() line: 515	
	SingleThreadEventExecutor$5.run() line: 918	
	ThreadExecutorMap$2.run() line: 74	
	FastThreadLocalRunnable.run() line: 30	
	VertxThread(Thread).run() line: 834	

````

this seems to be the one calling interrupt and then propagating that to other parts that trying to shutdown gracefully. does this help or shall I dig more?

**Comment by vietj** [comment]
yes this helps, to figure out what is going on.

This happens because of this in `KafkaSink` : https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaSink.java#L144

When the application is shutdown then the `KafkaSink` is shutdown concurrently because it does not wait for the completion. Since the `Vertx` instance is closed too, the Vert.x worker thread used for closing the producer will be interrupted as well.

I think that the `Vertx` instance should wait until all close `closeQuietly` methods are executed. Either synchronously (as it does not seem to be a Vert.x thread) or asynchronously: https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java#L43

e.g each `closeQuietly` could return a `CompletionStage`, then when `internalVertxInstance` is `true` the `Vertx#close` method will be called when all completion stages have been completed.
