### ISSUE TITLE
Admin Client API is behind current Kafka Admin Client

### ISSUE THREAD

**Issue by gmcrobert** [vert-x3/vertx-kafka-client#158]
It looks like the Vertx Kafka Admin Client API has not been updated since the initial move to using the Kafka Admin Client which appears to have been based on Kafka 0.11.0. The API has grown quite a lot since then and it would be useful to use some of the newer APIs in a consistent way through Vertx. Can I offer to update the Vertx Kafka Admin Client API to support a Vertx version of the full Kafka Admin Client at version 2.3.0 (or 2.4.0 if the support to 2.4.0 is going to take place soon)?

**Comment by ppatierno** [comment]
Any community effort is always welcome! :-)
I would start from the current supported 2.3.0 (even if the 2.4.0 is alredy out) and let's see how the PR evolves. Thanks!

**Comment by gmcrobert** [comment]
@ppatierno I think I will have some time to spend on doing this in the next few weeks. Three quick questions. Is it better to submit as a number of small PRs rather than the whole lot in a single PR and is there a preference of the order in which I should do them?

Third question, is there a pattern to determine which Kafka objects have vertx equivalents or are all the Kafka objects used by the API mapped to a vertx equivalent?

**Comment by ppatierno** [comment]
@gmcrobert that's cool!
Regarding PRs, having more small of them is simpler for reviewers and could speed up the process in order to have a feature merged into the library. So I would go in this direction instead of a huge big PR.
Every native Kafka object exposed through the API should be mapped to a corresponding Vert.x equivalent.
Regarding the PR, you should open them against the master but then we should be able to cherry-pick to the 3.9 branch. This is because the current master is focused on the next Vert.x 4 version but some components in the Strimzi land, see for example the bridge, are using Vert.x 3.x and there is no current plan to migrate code to the upcoming Vert.x 4.

**Comment by gmcrobert** [comment]
@ppatierno here is the first set of apis. The testing is a little challenging because the kafka cluster is created in the `beforeClass` annotated method so the tests have the potential to impact each other. If I am completely off the mark on the tests can you give me some guidance please. I couldn't find a lot of examples using the debezium test classes so had to resort to reading and understanding the API intent from the code.

I have a working version of the same code against the 3.9 branch. Do you want me to commit and push that up as well?

**Comment by gmcrobert** [comment]
@ppatierno sorry to nudge you but will you have a chance to glance over that PR so that I can get an idea whether it is in line with what is needed and I can then carry on with the next set of APIs?

**Comment by ppatierno** [comment]
@gmcrobert sorry for the huge delay!! Finally, I had a first pass.

**Comment by gmcrobert** [comment]
@ppatierno I have modified the PR and it is ready for review again please.
